apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: database
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: database
    
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: database-replica
  name: database-replica

spec:
  type: ClusterIP
  ports:
  - name: postgres-rep
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: database-replica