apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - webshop-beta.mbraptor.tech
    secretName: tls-mbraptor.tech
  rules:
  - host: webshop-beta.mbraptor.tech
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    run: frontend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      run: frontend
  replicas: 2
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
      - name: frontend
        image: 123456789.dkr.ecr.eu-central-1.amazonaws.com/webshop-frontend:$IMAGE_TAG
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
             path: /
             port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        livenessProbe:
          httpGet:
             path: /
             port: 5000
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: frontend
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50

---

apiVersion: v1
kind: Secret
data:
  tls.crt: ...
  tls.key: ...
metadata:
  name: tls-mbraptor.tech
type: kubernetes.io/tls